/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.diazcomesjoan;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException;
import static p1.t7.vista.diazcomesjoan.Main.gbd;
import p1t6modeldiazcomesjoan.Jugador;

/**
 *
 * @author micro
 */
public class EditarJugador extends javax.swing.JFrame {
    Jugador jugador = null;
    /**
     * Creates new form EditarJugador
     */
    public EditarJugador(Jugador jugador) {
        initComponents();
        
        this.jugador = jugador;
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        nomField.setText(jugador.getJugadorNom());
        cognomField.setText(jugador.getJugadorCog());
        sexeField.setText(jugador.getJugadorSexe());
        naixementField.setText(sdf.format(jugador.getJugadorNaixemet()));
        revisioField.setText(jugador.getJugadorRevisio()+"");
        adreçaField.setText(jugador.getJugadorAdreça());
        ibanField.setText(jugador.getJugadorIBAN());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        naixementField = new javax.swing.JTextField();
        nomField = new javax.swing.JTextField();
        adreçaField = new javax.swing.JTextField();
        cognomField = new javax.swing.JTextField();
        sexeField = new javax.swing.JTextField();
        ibanField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        revisioField = new javax.swing.JTextField();
        guardarBoto = new javax.swing.JButton();
        tornarBoto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar Jugador");

        jLabel3.setText("Nom");

        jLabel4.setText("Cognoms");

        jLabel5.setText("Sexe");

        jLabel6.setText("Naixement");

        jLabel7.setText("Adreça");

        jLabel8.setText("IBAN");

        naixementField.setToolTipText("00/00/0000");

        jLabel9.setText("Revisio");

        guardarBoto.setText("Guardar");
        guardarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotoActionPerformed(evt);
            }
        });

        tornarBoto.setText("Tornar");
        tornarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarBotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 58, Short.MAX_VALUE)
                                        .addComponent(tornarBoto)
                                        .addGap(58, 58, 58))
                                    .addComponent(cognomField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sexeField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(revisioField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(naixementField)
                                    .addComponent(nomField)
                                    .addComponent(adreçaField)
                                    .addComponent(ibanField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarBoto)
                                .addGap(167, 167, 167)))))
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cognomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(naixementField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adreçaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ibanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))))
                    .addComponent(revisioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBoto)
                    .addComponent(tornarBoto))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        naixementField.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tornarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornarBotoActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioJugadors gj = new GestioJugadors();
            gj.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tornarBotoActionPerformed

    private void guardarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotoActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        Date d = null;
        try {
            d = sdf.parse(naixementField.getText());
        
        
        Jugador gju = new Jugador(
            jugador.getJugadorId(), 
            nomField.getText(), 
            cognomField.getText(), 
            sexeField.getText(), 
            d, 
            ibanField.getText(), 
            null,
            Integer.parseInt(revisioField.getText()), 
            adreçaField.getText());
            
        
            System.out.println("Jugador guardar"+gju);
            
            try {
                gbd.editarJugador(gju);
                gbd.confirmarCanvis();
            } catch (GestorBDException ex) {
                Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ParseException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            GestioJugadors gj = new GestioJugadors();
            gj.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_guardarBotoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adreçaField;
    private javax.swing.JTextField cognomField;
    private javax.swing.JButton guardarBoto;
    private javax.swing.JTextField ibanField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField naixementField;
    private javax.swing.JTextField nomField;
    private javax.swing.JTextField revisioField;
    private javax.swing.JTextField sexeField;
    private javax.swing.JButton tornarBoto;
    // End of variables declaration//GEN-END:variables
}
