/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.diazcomesjoan;


import java.util.logging.Level;
import java.util.logging.Logger;
import p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException;
import static p1.t7.vista.diazcomesjoan.Main.gbd;
import p1t6modeldiazcomesjoan.Equip;

/**
 *
 * @author micro
 */
public class EditarEquip extends javax.swing.JFrame {
    Equip equip = null;
    /**
     * Creates new form EditarEquip
     */
    public EditarEquip(Equip equip) {
        initComponents();
        this.equip = equip;
        
        nomField.setText(equip.getNomEquip());
        tipusField.setText(equip.getEquipTipus());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        guardarBoto = new javax.swing.JButton();
        tornarBoto = new javax.swing.JButton();
        nomField = new javax.swing.JTextField();
        tipusField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Editar Equip");

        jLabel3.setText("Nom");

        jLabel4.setText("Tipus");

        guardarBoto.setText("Guardar");
        guardarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBotoActionPerformed(evt);
            }
        });

        tornarBoto.setText("Tornar");
        tornarBoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tornarBotoActionPerformed(evt);
            }
        });

        nomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipusField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(nomField))))
                .addGap(242, 242, 242))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(guardarBoto)
                .addGap(68, 68, 68)
                .addComponent(tornarBoto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarBoto)
                    .addComponent(tornarBoto))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBotoActionPerformed
                                                        
        // TODO add your handling code here:
        Equip geq = new Equip(
                equip.getIdEquip(),
                nomField.getText(),
                tipusField.getText()
        );
       
        try {
            gbd.editarEquip(geq);
            gbd.confirmarCanvis();
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarEquip.class.getName()).log(Level.SEVERE, null, ex);
        }
                
                
        GestioEquip ge;
        try {
            ge = new GestioEquip();
            ge.setVisible(true); 
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarEquip.class.getName()).log(Level.SEVERE, null, ex);
        }
                               
                
        

    }//GEN-LAST:event_guardarBotoActionPerformed

    private void tornarBotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tornarBotoActionPerformed
        
            // TODO add your handling code here:
            dispose();
        try {    
            GestioEquip ge = new GestioEquip();
            ge.setVisible(true);
        } catch (GestorBDException ex) {
            java.util.logging.Logger.getLogger(EditarEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tornarBotoActionPerformed

    private void nomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guardarBoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomField;
    private javax.swing.JTextField tipusField;
    private javax.swing.JButton tornarBoto;
    // End of variables declaration//GEN-END:variables
}
