/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.diazcomesjoan;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException;
import static p1.t7.vista.diazcomesjoan.Main.gbd;
import p1t6modeldiazcomesjoan.Jugador;

/**
 *
 * @author micro
 */
public class GestioJugadors extends javax.swing.JFrame {
    List<Jugador> jugadors = null;
    /**
     * Creates new form GestioJugadors
     * @throws p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException
     */
    public GestioJugadors() throws GestorBDException {
        initComponents();
        jugadors = gbd.trobarJugador();
        
        if (jugadors == null || jugadors.isEmpty()) {
          
        } else {
            omplirTaula();
        }

    }
    
     private void omplirTaula() {
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Nom");
        model.addColumn("Cognoms");
        model.addColumn("Sexe");
        model.addColumn("Naixement");
        model.addColumn("IBAN");
        model.addColumn("Revisio Medica");
        model.addColumn("Adreça");
        
        
        for(Jugador j : jugadors){
            model.addRow(new Object[]{
                j.getJugadorNom(), 
                j.getJugadorCog(), 
                j.getJugadorSexe(), 
                j.getJugadorNaixemet(),
                j.getJugadorIBAN(),
                j.getJugadorRevisio(),
                j.getJugadorAdreça()});
        }
        
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editarJugador = new javax.swing.JButton();
        botobuscarJugador = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        fieldbuscarJugador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        gestioEquip = new javax.swing.JButton();
        gestioTemporada = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("JUGADORS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        editarJugador.setText("Editar");
        editarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarJugadorActionPerformed(evt);
            }
        });

        botobuscarJugador.setText("Buscar");
        botobuscarJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botobuscarJugadorActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Botons cambiar pàgina");

        gestioEquip.setText("Gestio Equip");
        gestioEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioEquipActionPerformed(evt);
            }
        });

        gestioTemporada.setText("Gestio Temporada");
        gestioTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioTemporadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(editarJugador)
                        .addGap(108, 108, 108)
                        .addComponent(jButton3)
                        .addGap(0, 479, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(85, 85, 85)
                .addComponent(fieldbuscarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botobuscarJugador)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(gestioEquip)
                        .addGap(18, 18, 18)
                        .addComponent(gestioTemporada)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldbuscarJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botobuscarJugador)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gestioEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gestioTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarJugador)
                    .addComponent(jButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botobuscarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botobuscarJugadorActionPerformed
        // TODO add your handling code here:
        
        
        
        try {
            jugadors = gbd.trobarJugadorPerCamp(fieldbuscarJugador.getText());
        } catch (GestorBDException ex) {
            ex.printStackTrace();
        }
        
        if (jugadors == null || jugadors.isEmpty()) {
            
        } else {
            omplirTaula();
        }
    }//GEN-LAST:event_botobuscarJugadorActionPerformed

    private void editarJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarJugadorActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
         Jugador editarJugador = null;
            if (selectedRow != -1){
            
      
                EditarJugador ej = new EditarJugador(jugadors.get(selectedRow));
                ej.setVisible(true);
                dispose();
            }
            
//        try {
//            editarJugadors = gbd.editarJugador();
//        } catch (GestorBDException ex) {
//            ex.printStackTrace();
//        }
//        
//        if (editarJugadors == null || editarJugadors.isEmpty()) {
//           
//        } else {
//            omplirTaula(editarJugadors);
//        }
    }//GEN-LAST:event_editarJugadorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
         
            if (selectedRow != -1){
               
      
            try {
                gbd.eliminarJugador(jugadors.get(selectedRow).getJugadorId());
                gbd.confirmarCanvis();
                
                jugadors.remove(selectedRow);
                
                omplirTaula();
                
            } catch (GestorBDException ex) {
                Logger.getLogger(GestioJugadors.class.getName()).log(Level.SEVERE, null, ex);
            }
               
                
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gestioEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioEquipActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioEquip ge = new GestioEquip();
            ge.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestioEquipActionPerformed

    private void gestioTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioTemporadaActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioTemporada gt = new GestioTemporada();
            gt.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestioTemporadaActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botobuscarJugador;
    private javax.swing.JButton editarJugador;
    private javax.swing.JTextField fieldbuscarJugador;
    private javax.swing.JButton gestioEquip;
    private javax.swing.JButton gestioTemporada;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
