/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.diazcomesjoan;


import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException;
import static p1.t7.vista.diazcomesjoan.Main.gbd;
import p1t6modeldiazcomesjoan.Equip;


/**
 *
 * @author micro
 */
public class GestioEquip extends javax.swing.JFrame {

    List<Equip> equips = null;
    /**
     * Creates new form GestioEquip
     * @throws p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException
     */
    public GestioEquip() throws GestorBDException {
        initComponents();
        equips = gbd.trobarEquip();
        
        if (equips == null || equips.isEmpty()) {
            
        } else {
            omplirTaula();
        }
    }
    
    private void omplirTaula() {
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Nom");
        model.addColumn("Tipus");

        
        
        for(Equip e : equips){
            model.addRow(new Object[]{
                e.getNomEquip(), 
                e.getEquipTipus(),
                });
        }
        
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarEquip = new javax.swing.JButton();
        fieldbuscarEquip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editarEquip = new javax.swing.JButton();
        botobuscarEquip = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gestioEquip = new javax.swing.JButton();
        gestioTemporada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eliminarEquip.setText("Eliminar");
        eliminarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarEquipActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("EQUIP");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        editarEquip.setText("Editar");
        editarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarEquipActionPerformed(evt);
            }
        });

        botobuscarEquip.setText("Buscar");
        botobuscarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botobuscarEquipActionPerformed(evt);
            }
        });

        jLabel2.setText("Botons cambiar pàgina");

        gestioEquip.setText("Gestio Jugador");
        gestioEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioEquipActionPerformed(evt);
            }
        });

        gestioTemporada.setText("Gestio Temporada");
        gestioTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioTemporadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(editarEquip)
                        .addGap(108, 108, 108)
                        .addComponent(eliminarEquip)
                        .addGap(0, 471, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(fieldbuscarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botobuscarEquip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gestioEquip)
                        .addGap(18, 18, 18)
                        .addComponent(gestioTemporada)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldbuscarEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botobuscarEquip))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gestioEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gestioTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarEquip)
                    .addComponent(eliminarEquip))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarEquipActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1){
            

           
            try {
                gbd.eliminarEquip(equips.get(selectedRow).getIdEquip());
                gbd.confirmarCanvis();

                equips.remove(selectedRow);

                omplirTaula();
            } catch (GestorBDException ex) {
                java.util.logging.Logger.getLogger(GestioEquip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
               

            

        }
    }//GEN-LAST:event_eliminarEquipActionPerformed

    private void editarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarEquipActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        Equip editarEquip = null;
        if (selectedRow != -1){
            

            EditarEquip eq = new EditarEquip(equips.get(selectedRow));
            eq.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_editarEquipActionPerformed

    private void botobuscarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botobuscarEquipActionPerformed
        // TODO add your handling code here:
       

        try {
            equips = gbd.trobarEquipPerCamp(fieldbuscarEquip.getText());
        } catch (GestorBDException ex) {
            ex.printStackTrace();
        }

        if (equips == null || equips.isEmpty()) {
            
        } else {
            omplirTaula();
        }
    }//GEN-LAST:event_botobuscarEquipActionPerformed

    private void gestioEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioEquipActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioJugadors gj = new GestioJugadors();
            gj.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestioEquipActionPerformed

    private void gestioTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioTemporadaActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioTemporada gt = new GestioTemporada();
            gt.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestioTemporadaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botobuscarEquip;
    private javax.swing.JButton editarEquip;
    private javax.swing.JButton eliminarEquip;
    private javax.swing.JTextField fieldbuscarEquip;
    private javax.swing.JButton gestioEquip;
    private javax.swing.JButton gestioTemporada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
