/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1.t7.vista.diazcomesjoan;

import p1t6modeldiazcomesjoan.Temporada;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException;
import static p1.t7.vista.diazcomesjoan.Main.gbd;
import p1t6modeldiazcomesjoan.Equip;


/**
 *
 * @author micro
 */
public class GestioTemporada extends javax.swing.JFrame {

    List<Temporada> temporades = null;
    /**
     * Creates new form GestioTemporada
     * @throws p1.t6.interficiepersistencia.diazcomesjoan.GestorBDException
     */
    public GestioTemporada() throws GestorBDException {
        initComponents();
        temporades = gbd.trobarTemporada();
        
        if (temporades == null || temporades.isEmpty()) {
            
        } else {
            omplirTaula();
        }
    }
    
     private void omplirTaula() {
        
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Any");

        
        
        for(Temporada temp : temporades){
            model.addRow(new Object[]{
                temp.getTemporada()
                });
        }
        
        jTable1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarTemporada = new javax.swing.JButton();
        fieldbuscarTemporada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editarTemporada = new javax.swing.JButton();
        botobuscarTemporada = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gestioJugador = new javax.swing.JButton();
        gestioEquip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        eliminarTemporada.setText("Eliminar");
        eliminarTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarTemporadaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("TEMPORADA");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        editarTemporada.setText("Editar");
        editarTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTemporadaActionPerformed(evt);
            }
        });

        botobuscarTemporada.setText("Buscar");
        botobuscarTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botobuscarTemporadaActionPerformed(evt);
            }
        });

        jLabel2.setText("Botons cambiar pàgina");

        gestioJugador.setText("Gestio Jugador");
        gestioJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioJugadorActionPerformed(evt);
            }
        });

        gestioEquip.setText("Gestio Equip");
        gestioEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestioEquipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(editarTemporada)
                        .addGap(108, 108, 108)
                        .addComponent(eliminarTemporada)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(fieldbuscarTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botobuscarTemporada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(gestioJugador)
                        .addGap(18, 18, 18)
                        .addComponent(gestioEquip)
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldbuscarTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botobuscarTemporada))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gestioJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gestioEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarTemporada)
                    .addComponent(eliminarTemporada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarTemporadaActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow != -1){
            

            try {
                gbd.eliminarTemporada(temporades.get(selectedRow).getTemporada());
                gbd.confirmarCanvis();

                temporades.remove(selectedRow);

                omplirTaula();
            } catch (GestorBDException ex) {
                java.util.logging.Logger.getLogger(GestioTemporada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_eliminarTemporadaActionPerformed

    private void editarTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTemporadaActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        Temporada editarTemporada = null;
        if (selectedRow != -1){
            

            EditarTemporada temp = new EditarTemporada(temporades.get(selectedRow));
            temp.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_editarTemporadaActionPerformed

    private void botobuscarTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botobuscarTemporadaActionPerformed
        // TODO add your handling code here:
        

        try {
            temporades = gbd.trobarTemporadaperCamp(fieldbuscarTemporada.getText());
        } catch (GestorBDException ex) {
            ex.printStackTrace();
        }

        if (temporades == null || temporades.isEmpty()) {
            
        } else {
            omplirTaula();
        }
    }//GEN-LAST:event_botobuscarTemporadaActionPerformed

    private void gestioJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioJugadorActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioJugadors gj = new GestioJugadors();
            gj.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarJugador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestioJugadorActionPerformed

    private void gestioEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestioEquipActionPerformed
        // TODO add your handling code here:
        dispose();
        try {
            GestioEquip ge = new GestioEquip();
            ge.setVisible(true);
        } catch (GestorBDException ex) {
            Logger.getLogger(EditarEquip.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_gestioEquipActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botobuscarTemporada;
    private javax.swing.JButton editarTemporada;
    private javax.swing.JButton eliminarTemporada;
    private javax.swing.JTextField fieldbuscarTemporada;
    private javax.swing.JButton gestioEquip;
    private javax.swing.JButton gestioJugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
